### ISSUE TITLE
./05-GEM-parse.sh error

### ISSUE THREAD

**Issue by feltus** [wpoehlm/PBS-GEM#1]
[ffeltus@login001 Logs]$ cat GEM.err
mv: cannot stat ‘t_data.ctab’: No such file or directory
mv: cannot stat ‘SRR1732329.String.counts’: No such file or directory
mv: cannot stat ‘t_data.ctab’: No such file or directory
mv: cannot stat ‘SRR1747220.String.counts’: No such file or directory
mv: cannot stat ‘t_data.ctab’: No such file or directory
mv: cannot stat ‘SRR1813870.String.counts’: No such file or directory
mv: cannot stat ‘t_data.ctab’: No such file or directory
mv: cannot stat ‘SRR2068820.String.counts’: No such file or directory
mv: cannot stat ‘t_data.ctab’: No such file or directory
mv: cannot stat ‘SRR771467.String.counts’: No such file or directory
  File "/scratch2/ffeltus/lcm/PBS-GEM/Task-Files/ST_ttab_parse.py", line 13
    print 'TranscriptID' + '\t' + 'FPKM'
                       ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by feltus** [comment]
I think there is a Python error and there is no t_data.ctab

e2t.ctab     i2t.ctab     SRR1732329.hisat2.StringTie.hits.bam.gtf
e_data.ctab  i_data.ctab

**Comment by wpoehlm** [comment]
Python2 should be the default on Palmetto, do you have a different one set in your bashrc or something?  Also, did you try running the GEM merge script twice?  I'll re run everything right now to see if it works for me

**Comment by wpoehlm** [comment]
@feltus just tested and everything worked for me.  I'll make sure that a python2 module is loaded in the GEM parse script.
